// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: xiaoyuan_tts/v1/xiaoyuan_tts_v1_api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` //会话id
	UserId         string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         //用户id
	Text           string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`                                           //小元回复的文本内容
	SpeakerId      int32  `protobuf:"varint,4,opt,name=speaker_id,json=speakerId,proto3" json:"speaker_id,omitempty"`               //合成的人声
}

func (x *ExecReq) Reset() {
	*x = ExecReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecReq) ProtoMessage() {}

func (x *ExecReq) ProtoReflect() protoreflect.Message {
	mi := &file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecReq.ProtoReflect.Descriptor instead.
func (*ExecReq) Descriptor() ([]byte, []int) {
	return file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *ExecReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ExecReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ExecReq) GetSpeakerId() int32 {
	if x != nil {
		return x.SpeakerId
	}
	return 0
}

type ExecResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` //会话id
	UserId         string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         //用户id
	WavData        []byte `protobuf:"bytes,3,opt,name=wav_data,json=wavData,proto3" json:"wav_data,omitempty"`                      //合成音频文件内容 接收字节数据写入文件 以后缀wav命名
}

func (x *ExecResp) Reset() {
	*x = ExecResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResp) ProtoMessage() {}

func (x *ExecResp) ProtoReflect() protoreflect.Message {
	mi := &file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResp.ProtoReflect.Descriptor instead.
func (*ExecResp) Descriptor() ([]byte, []int) {
	return file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResp) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ExecResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecResp) GetWavData() []byte {
	if x != nil {
		return x.WavData
	}
	return nil
}

var File_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto protoreflect.FileDescriptor

var file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDesc = []byte{
	0x0a, 0x29, 0x78, 0x69, 0x61, 0x6f, 0x79, 0x75, 0x61, 0x6e, 0x5f, 0x74, 0x74, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x78, 0x69, 0x61, 0x6f, 0x79, 0x75, 0x61, 0x6e, 0x5f, 0x74, 0x74, 0x73, 0x5f, 0x76,
	0x31, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x62, 0x72, 0x61,
	0x69, 0x6e, 0x2e, 0x6e, 0x6c, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x79,
	0x75, 0x61, 0x6e, 0x54, 0x54, 0x53, 0x2e, 0x76, 0x31, 0x22, 0x7e, 0x0a, 0x07, 0x45, 0x78, 0x65,
	0x63, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x70,
	0x65, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x08, 0x45, 0x78, 0x65,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x61, 0x76, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x77, 0x61, 0x76, 0x44, 0x61,
	0x74, 0x61, 0x32, 0x5e, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x12, 0x57, 0x0a, 0x04, 0x45, 0x78, 0x65,
	0x63, 0x12, 0x25, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x2e, 0x6e, 0x6c, 0x70, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x79, 0x75, 0x61, 0x6e, 0x54, 0x54, 0x53, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x6e,
	0x2e, 0x6e, 0x6c, 0x70, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x78, 0x69, 0x61, 0x6f, 0x79, 0x75, 0x61,
	0x6e, 0x54, 0x54, 0x53, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x2e, 0x61, 0x69, 0x6d, 0x61, 0x6c, 0x6c,
	0x2d, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x2f, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x2f, 0x6e, 0x6c, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x78, 0x69, 0x61, 0x6f, 0x79, 0x75, 0x61, 0x6e, 0x5f, 0x74, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDescOnce sync.Once
	file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDescData = file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDesc
)

func file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDescGZIP() []byte {
	file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDescOnce.Do(func() {
		file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDescData)
	})
	return file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDescData
}

var file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_goTypes = []interface{}{
	(*ExecReq)(nil),  // 0: brain.nlp.api.xiaoyuanTTS.v1.ExecReq
	(*ExecResp)(nil), // 1: brain.nlp.api.xiaoyuanTTS.v1.ExecResp
}
var file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_depIdxs = []int32{
	0, // 0: brain.nlp.api.xiaoyuanTTS.v1.API.Exec:input_type -> brain.nlp.api.xiaoyuanTTS.v1.ExecReq
	1, // 1: brain.nlp.api.xiaoyuanTTS.v1.API.Exec:output_type -> brain.nlp.api.xiaoyuanTTS.v1.ExecResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_init() }
func file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_init() {
	if File_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_goTypes,
		DependencyIndexes: file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_depIdxs,
		MessageInfos:      file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_msgTypes,
	}.Build()
	File_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto = out.File
	file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_rawDesc = nil
	file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_goTypes = nil
	file_xiaoyuan_tts_v1_xiaoyuan_tts_v1_api_proto_depIdxs = nil
}
